# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-25 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musiControl', '0002_album_playing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='playing',
            field=models.NullBooleanField(),
        ),
    ]
